First pass engine structure
isee-systems/sd-ai pull request #2
Opened 2024-12-23 19:51 UTC by dgcoskip

Focus mainly on engine structure in app.js
Have a look at the the minimum viable engine `predprey` in engines folder

` curl  localhost:3000/api/v1/engines/default/parameters | jq . `
` curl -X POST localhost:3000/api/v1/engines/default/generate -H "Content-type: application/json" -d '{"format": "sd-json", "prompt": "when death rate goes up, population decreases"}' | jq . `

Next Steps
- test deeper features implemented in default like model selection
- take a stab at documenting sd-json data structure
- understand how were we want reasoning/documentation implemented in input and output sd-json
-

2024-12-24 16:29 UTC, wasbridge requested changes
In general I really like this.  I think moving to class based engines, and getting as much smarts out of app.js and into routes/v1 would make it even better.  

Finally, I think the /ap1/v1/initialize call needs to return the list of possible engines, and then for each engine, the parameters, and for each parameter with a picklist of options, a list for that picklist.  By doing that I can have the Stella client (which will let you ideally work with all the engines and all of the options) create the UI in response to the current state of the service.

Let me know how I can help

2024-12-24 16:29 UTC, wasbridge commented on app.js
> +app.get("/api/v1/engines/:engine/parameters", async (req, res) => {
I prefer to put each API call in its own file named by its route.  This helps me easily browse the API from a code perspective

2024-12-24 16:29 UTC, wasbridge commented on app.js
> +    "format": "type=string, default='sd-json', options are <sd-json|xmile>",
I think for now we stick with JSON only.  Lets wait for someone to really need the XMILE before we write a generic XMILE parser in JS.

2024-12-24 16:29 UTC, wasbridge commented on engines/default/engine.js
> +import utils from './utils.js'
This may be my OO-crazy speaking, but can we make Engine be a class with two required public methods, additionalParameters() and generate()?

2024-12-24 16:29 UTC, wasbridge commented on engines/predprey/engine.js
> +export function additionalParameters () {
I like this one.  I think if this was a class it would be perfect

2025-01-06 22:13 UTC, dgcoskip commented on app.js
> +    "format": "type=string, default='sd-json', options are <sd-json|xmile>",
This format is actually the output format. I think since you already implemented an xmile export it's probably worth keeping around.

2025-01-06 22:13 UTC, dgcoskip commented on app.js
> +app.get("/api/v1/engines/:engine/parameters", async (req, res) => {
Sounds good to me!

2025-01-06 22:21 UTC, dgcoskip commented
1. switch to class-based instead of function based engines
2. modify `/engines` endpoint to include information from additional_parameters
this will allow stella to construct a dynamic engine selection ui (cool!), see: https://github.com/isee-systems/sd-ai/blob/e2f808f7e23ee865276a48f9e655ad54967b1893/app.js#L34
3. moving all endpoints to their own routes/v1 files, like we had before
4. make sure all features (like model selection, api keys, etc) in `default` engine still work properly
5. [probably needs to be me?] first pass at comodel-copilot engine, thinking through knowledge a bit
6. take a stab at documenting sd-json data structure
7. understand how were we want reasoning/documentation implemented in input and output sd-json

2025-01-07 19:50 UTC, merged